# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases
  - 7.2

# optionally specify a list of environments, for example to test different RDBMS
env:
  - DB=mysql

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS test;" -uroot; fi
  # update root password
  - if [[ "$DB" == "mysql" ]]; then mysql -e "set password for 'root'@'localhost'=password('123456');" -uroot; fi
  # git clone
  - cd ~
  - git clone https://github.com/jasydong/phpunit_demo.git
  - cd phpunit_demo

# use phpunit to test
script: phpunit --configuration tests/phpunit.xml --coverage-text

# configure notifications (email, IRC, campfire etc)
notifications:
  email: "jasydong@qq.com"
